### ISSUE TITLE
Go Node segfaults when binary is not found

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#205]
## 🙂 Expected behavior

Raise a readable error

## 🫠 Actual behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4e0660]

goroutine 34 [running]:
os.(*ProcessState).sys(...)
	/usr/local/go/src/os/exec_posix.go:91
os.(*ProcessState).Sys(...)
	/usr/local/go/src/os/exec.go:170
github.com/cartesi/rollups-node/internal/services.Service.Start({{0x51e257, 0xe}, 0x2afd, {0x52267e, 0x1e}, {0x0, 0x0, 0x0}, {0xc000142000, 0x4c, ...}}, ...)
	/home/gligneul/cartesi/rollups-node/internal/services/service.go:70 +0x220
github.com/cartesi/rollups-node/internal/services.Run.func1()
	/home/gligneul/cartesi/rollups-node/internal/services/service.go:124 +0xb9
created by github.com/cartesi/rollups-node/internal/services.Run in goroutine 1
	/home/gligneul/cartesi/rollups-node/internal/services/service.go:120 +0x305
exit status 2
```

## 🧪 Minimal test case

Start the Go node without one of the binaries in the PATH.

## 🌎 Environment

main

**Comment by gligneul** [comment]
Suggested solution: https://github.com/gligneul/nonodo/commit/cc1682f21d4986fc98c9cc99c61f05484a32af04
